server {
    listen 80;

    client_max_body_size 1G;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/users/ {
        proxy_pass http://user-service:8001/api/users/;
    }

    location /api/videos/ {
        proxy_pass http://video-service:8002/api/videos/;
    }

    location /api/analytics/ {
        proxy_pass http://analytics-service:8003/api/analytics/;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}