
services:

  user-service:
    image: iapsingh/microservices-cdn-semver-user:1.0.0
    container_name: user-service
    restart: always
    env_file: .env
    ports:
      - "8001:8001"
    networks:
      - scroll-network

  video-service:
    image: iapsingh/microservices-cdn-semver-video:1.0.0
    container_name: video-service
    restart: always
    env_file: .env
    ports:
      - "8002:8002"
    networks:
      - scroll-network

  analytics-service:
    image: iapsingh/microservices-cdn-semver-analytics:1.0.0
    container_name: analytics-service
    restart: always
    env_file: .env
    ports:
      - "8003:8003"
    networks:
      - scroll-network

  frontend:
    image: iapsingh/microservices-cdn-semver-frontend:1.0.0
    container_name: frontend-service
    restart: always
    ports:
      - "8000:80"
    networks:
      - scroll-network

networks:
  scroll-network: